### PR TITLE
Add msp430 AdHoc Network Code

### PR DESCRIPTION
**Pull request by Shibbywan**
Should probably confirm 100% that we can add this code and make sure everyone is ok with it @ChrisDubeau @aidanbush @reboss @ElliottSobek

### CODE REVIEW

**Comment by aidanbush** [comment]
do you want us to all comment saying we're ok with it before we merge the pull request?

**Comment by Shibbywan** [comment]
I think that's probably the best idea, It's not urgent though. If anyone knows how to upload git commit history that would be cool too.

**Comment by ChrisDubeau** [comment]
I'm good with doing this commit.

**Comment by reboss** [comment]
I'm just going to push directly from our repo on students so all our commit history is there.  Consider it a merge :)

**Pull request closed without merging**
